---
# tasks file for install_jenkins
- name: Add Jenkins's official GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  apt_repository:
    repo: >- 
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] 
      https://pkg.jenkins.io/debian-stable binary/
    filename: jenkins
    state: present

- name: Install Jenkins and related packages
  apt:
    name: jenkins
    state: present
    update_cache: yes